### ISSUE TITLE
Regexp matching site styles don't show up in toolbar button when they match

### ISSUE THREAD

**Issue by JasonBarnabe** [stylish-userstyles/stylish#204]
When on forum.userstyles.org,

``` css
@-moz-document regexp(".*forum.*"){*{color:red!important;}}
```

Should show up as a site-matching style.
