### ISSUE TITLE
[SOLVED] "There's an error with your CSS code, please review it." When trying to publish my style

### ISSUE THREAD

**Issue by farisfaikar** [stylish-userstyles/stylish#346]
I need help when trying to publish my own style. Here's the CSS code

```css
#logo-icon
{
  content: url("https://media.tenor.com/65mRO-L3k2EAAAAj/spinning-maxwell.gif") !important;
  width: 120px;
  height: 35px;
  object-fit: cover;
}

ytd-topbar-logo-renderer
{
  width: 0%;
}
```
I've tested that code and it works flawlessly for me when I try using it as a private style. But when I try to publish it, it gave me this error

> [!CAUTION]
> There's an error with your CSS code, please review it.

How do I fix this and publish my style properly? Thanks!

**Comment by FeuFeuAngel** [comment]
I am not pro myself at css and try uploud a dark mode version for webtoon.com

```css
#content {
  background-color: #323232;
}
.viewer_lst .day_info {
    color: white;
}
.viewer_lst .dsc_encourage {
    color: white;
}
.comment_area .creator_note .title {
    color: whitesmoke;
}
.comment_area .creator_note .author_text {
    color: whitesmoke;
}
:root {
      wcc-white: #323232;
      wcc-black: #ffffff;
      wcc-text-12: whitesmoke;
      wcc-text-13: whitesmoke;
    	wcc-text-25: whitesmoke;
}
a{
  color:whitesmoke;
}
```

i get the same error,
